apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: test
        image: registry.hub.docker.com/library/python
        command: ['/bin/sh','-c']
        args: ['env; date;sleep 60000;date']
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Never
  backoffLimit: 0